### ISSUE TITLE
Mod does not work on 1.21.1

### ISSUE THREAD

**Issue by Striker183** [InterurbanDev/MinecraftRailroadBlocks#47]
**Describe the bug**
I installed the mod for 1.21.1 with the Fabric Loader. Unfortunately it doesn't start.

**To Reproduce**
1. install mod
2. start Minecraft
3. crash

**Expected behavior**
//

**Screenshots**
https://ibb.co/7RCh7FY

**Additional Information (please complete the following information):**
- Minecraft Version: 1.21.1
- Mod Version: 0.6.1
- Mod Loader: Fabric
- Mod Loader Version: 0.16.9

**Additional context**
With 0.6.0 it works

**Comment by InterurbanDev** [comment]
I've issued a new patch to address the issue. Minecraft should now load with version 0.6.2 of Railroad Blocks.
The issue was due to the formatting of the version range, however, v0.6.0 also used the same formatting, so I'm not sure what changed. Regardless, the new version now uses the proper format and should work.

Thank you for alerting me to this issue!
